package au.edu.rmit.sept.webapp.service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

import au.edu.rmit.sept.webapp.model.Event_Feedback;
import au.edu.rmit.sept.webapp.repository.FeedbackRepository;

@Service
public class FeedbackServiceImpl implements FeedbackService {

    private final FeedbackRepository feedbackRepository;

    public FeedbackServiceImpl(FeedbackRepository feedbackRepository) {
        this.feedbackRepository = feedbackRepository;
    }

    @Override
    public Event_Feedback submitFeedback(int eventId, int userId, int rating, String comments) {
        // Validate rating
        if (rating < 1 || rating > 5) {
            throw new IllegalArgumentException("Rating must be between 1 and 5");
        }

        // Clean up comments (remove null, trim whitespace)
        String cleanedComments = comments != null ? comments.trim() : "";
        
        Event_Feedback feedback = new Event_Feedback(
            0, // ID will be generated by database
            eventId,
            userId,
            rating,
            cleanedComments,
            LocalDateTime.now()
        );

        return feedbackRepository.save(feedback);
    }

    @Override
    public List<Event_Feedback> getEventFeedback(int eventId) {
        return feedbackRepository.findByEventId(eventId);
    }

    @Override
    public Optional<Event_Feedback> getUserEventFeedback(int eventId, int userId) {
        return feedbackRepository.findByEventIdAndUserId(eventId, userId);
    }

    @Override
    public boolean hasUserProvidedFeedback(int eventId, int userId) {
        return feedbackRepository.findByEventIdAndUserId(eventId, userId).isPresent();
    }

    @Override
    public double getAverageRating(int eventId) {
        return feedbackRepository.getAverageRatingByEventId(eventId);
    }

    @Override
    public List<Event_Feedback> getUserFeedback(int userId) {
        return feedbackRepository.findByUserId(userId);
    }
}